# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.2
xcode_project: Coordinator.xcodeproj
xcode_scheme: Coordinator
xcode_destination: name=iPhone X,OS=12.1
script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Coordinator.xcworkspace -scheme Coordinator-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
